
services:
  backend:
    container_name: smit-autograde-backend
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    container_name: smit-autograde-frontend
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

